trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
 pathToProject: './SMTC.API.TaxaJuros/SMTC.API.TaxaJuros.csproj'

steps:
  - task: DotNetCoreCLI@2
    displayName:  'Restore das dependÃªncias'
    inputs:
      command: 'restore'
      projects: '$(pathToProject)'
      feedsToUse: 'select'
  - task: DotNetCoreCLI@2
    displayName:  'Build do projeot'
    inputs:
      command: 'build'
      projects: '$(pathToProject)'